export const RESOURCE_RESET = '@resx/RESET';
export const RESOURCE_DESTROY_NS = '@resx/DESTROY_NS';

export const RESOURCE_FIND_REQUEST = '@resx/FIND';
export const RESOURCE_FIND_SUCCESS = '@resx/FIND_SUCCESS';
export const RESOURCE_FIND_FAILURE = '@resx/FIND_FAILURE';

export const RESOURCE_GET_REQUEST = '@resx/GET';
export const RESOURCE_GET_SUCCESS = '@resx/GET_SUCCESS';
export const RESOURCE_GET_FAILURE = '@resx/GET_FAILURE';

export const RESOURCE_CREATE_REQUEST = '@resx/CREATE';
export const RESOURCE_CREATE_SUCCESS = '@resx/CREATE_SUCCESS';
export const RESOURCE_CREATE_FAILURE = '@resx/CREATE_FAILURE';

export const RESOURCE_UPDATE_REQUEST = '@resx/UPDATE';
export const RESOURCE_UPDATE_SUCCESS = '@resx/UPDATE_SUCCESS';
export const RESOURCE_UPDATE_FAILURE = '@resx/UPDATE_FAILURE';

export const RESOURCE_PATCH_REQUEST = '@resx/PATCH';
export const RESOURCE_PATCH_SUCCESS = '@resx/PATCH_SUCCESS';
export const RESOURCE_PATCH_FAILURE = '@resx/PATCH_FAILURE';

export const RESOURCE_REMOVE_REQUEST = '@resx/REMOVE';
export const RESOURCE_REMOVE_SUCCESS = '@resx/REMOVE_SUCCESS';
export const RESOURCE_REMOVE_FAILURE = '@resx/REMOVE_FAILURE';

export const requestTypes = [
  RESOURCE_FIND_REQUEST,
  RESOURCE_GET_REQUEST,
  RESOURCE_CREATE_REQUEST,
  RESOURCE_UPDATE_REQUEST,
  RESOURCE_PATCH_REQUEST,
  RESOURCE_REMOVE_REQUEST,
];

export const successTypes = [
  RESOURCE_FIND_SUCCESS,
  RESOURCE_GET_SUCCESS,
  RESOURCE_CREATE_SUCCESS,
  RESOURCE_UPDATE_SUCCESS,
  RESOURCE_PATCH_SUCCESS,
  RESOURCE_REMOVE_SUCCESS,
];

export const errorTypes = [
  RESOURCE_FIND_FAILURE,
  RESOURCE_GET_FAILURE,
  RESOURCE_CREATE_FAILURE,
  RESOURCE_UPDATE_FAILURE,
  RESOURCE_PATCH_FAILURE,
  RESOURCE_REMOVE_FAILURE,
];
