export const RESOURCE_RESET = '@resource/RESET';

export const RESOURCE_FIND_REQUEST = '@resource/FIND';
export const RESOURCE_FIND_SUCCESS = '@resource/FIND_SUCCESS';
export const RESOURCE_FIND_FAILURE = '@resource/FIND_FAILURE';

export const RESOURCE_GET_REQUEST = '@resource/GET';
export const RESOURCE_GET_SUCCESS = '@resource/GET_SUCCESS';
export const RESOURCE_GET_FAILURE = '@resource/GET_FAILURE';

export const RESOURCE_CREATE_REQUEST = '@resource/CREATE';
export const RESOURCE_CREATE_SUCCESS = '@resource/CREATE_SUCCESS';
export const RESOURCE_CREATE_FAILURE = '@resource/CREATE_FAILURE';

export const RESOURCE_UPDATE_REQUEST = '@resource/UPDATE';
export const RESOURCE_UPDATE_SUCCESS = '@resource/UPDATE_SUCCESS';
export const RESOURCE_UPDATE_FAILURE = '@resource/UPDATE_FAILURE';

export const RESOURCE_PATCH_REQUEST = '@resource/PATCH';
export const RESOURCE_PATCH_SUCCESS = '@resource/PATCH_SUCCESS';
export const RESOURCE_PATCH_FAILURE = '@resource/PATCH_FAILURE';

export const RESOURCE_REMOVE_REQUEST = '@resource/REMOVE';
export const RESOURCE_REMOVE_SUCCESS = '@resource/REMOVE_SUCCESS';
export const RESOURCE_REMOVE_FAILURE = '@resource/REMOVE_FAILURE';

export const requestTypes = [
  RESOURCE_FIND_REQUEST,
  RESOURCE_GET_REQUEST,
  RESOURCE_CREATE_REQUEST,
  RESOURCE_UPDATE_REQUEST,
  RESOURCE_PATCH_REQUEST,
  RESOURCE_REMOVE_REQUEST,
];

export const successTypes = [
  RESOURCE_FIND_SUCCESS,
  RESOURCE_GET_SUCCESS,
  RESOURCE_CREATE_SUCCESS,
  RESOURCE_UPDATE_SUCCESS,
  RESOURCE_PATCH_SUCCESS,
  RESOURCE_REMOVE_SUCCESS,
];

export const errorTypes = [
  RESOURCE_FIND_FAILURE,
  RESOURCE_GET_FAILURE,
  RESOURCE_CREATE_FAILURE,
  RESOURCE_UPDATE_FAILURE,
  RESOURCE_PATCH_FAILURE,
  RESOURCE_REMOVE_FAILURE,
];
